import { env } from '$env/dynamic/public'
import type { BooleanDeviceState, DeviceMetadata, NumberDeviceState } from './lib/device-state'
import { writable, type Writable } from 'svelte/store'

export const configuration = [
  {
    roomId: 'guest',
    deviceId: 'guestLight',
    displayName: 'Guest light',
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    readTopic: env.PUBLIC_GUEST_LIGHT_FROM,
    writeTopic: env.PUBLIC_GUEST_LIGHT_TO,
    deviceType: 'light',
    type: 'boolean',
  },
  {
    roomId: 'guest',
    deviceId: 'guestHeating',
    displayName: 'Guest heating',
    readTopic: env.PUBLIC_GUEST_HEAT_VALVE,
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(), 
    deviceType: 'heating',
    type: 'boolean',
  },
  {
    roomId: 'guest',
    deviceId: 'guestTemperature',
    displayName: 'Guest temperature',
    readTopic: env.PUBLIC_GUEST_TEMP,
    store: writable<NumberDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'temperature',
    type: 'number',
  },
  {
    roomId: 'guest',
    deviceId: 'guestSetTemperature',
    displayName: 'Guest set temperature',
    readTopic: env.PUBLIC_GUEST_SET_TEMP,
    store: writable<NumberDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'setTemperature',
    type: 'number',
  },
  {
    roomId: 'guest',
    deviceId: 'guestPresence',
    displayName: 'Guest presence',
    readTopic: env.PUBLIC_GUEST_PRESENCE,
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'presence',
    type: 'boolean',
  },
  {
    roomId: 'guest',
    deviceId: 'guestBlind',
    displayName: 'Guest blind',
    stateStore: writable<NumberDeviceState>('not-initialized'),
    commandStore: writable<NumberDeviceState>('not-initialized'),
    rawStateStore: writable<string>(),
    rawCommandStore: writable<string>(),
    readTopic: env.PUBLIC_GUEST_BLIND_FROM,
    writeTopic: env.PUBLIC_GUEST_BLIND_TO,
    deviceType: 'blind',
    type: 'number',
  },
  {
    roomId: 'living',
    deviceId: 'livingLight',
    displayName: 'Living light',
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    readTopic: env.PUBLIC_LIVING_LIGHT_FROM,
    writeTopic: env.PUBLIC_LIVING_LIGHT_TO,
    deviceType: 'light',
    type: 'boolean',
  },
  {
    roomId: 'living',
    deviceId: 'livingHeating',
    displayName: 'Living heating',
    readTopic: env.PUBLIC_LIVING_HEAT_VALVE,
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'heating',
    type: 'boolean',
  },
  {
    roomId: 'living',
    deviceId: 'livingTemperature',
    displayName: 'Living temperature',
    readTopic: env.PUBLIC_LIVING_TEMP,
    store: writable<NumberDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'temperature',
    type: 'number',
  },
  {
    roomId: 'living',
    deviceId: 'livingSetTemperature',
    displayName: 'Living set temperature',
    readTopic: env.PUBLIC_LIVING_SET_TEMP,
    store: writable<NumberDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'setTemperature',
    type: 'number',
  },
  {
    roomId: 'living',
    deviceId: 'livingEntranceLight',
    displayName: 'Living entrance light',
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    readTopic: env.PUBLIC_LIVING_ENTRANCE_LIGHT_FROM,
    writeTopic: env.PUBLIC_LIVING_ENTRANCE_LIGHT_TO,
    deviceType: 'light',
    type: 'boolean',
  },
  {
    roomId: 'living',
    deviceId: 'livingPrsence',
    displayName: 'Living presence',
    readTopic: env.PUBLIC_LIVING_PRESENCE,
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'presence',
    type: 'boolean',
  },
  {
    roomId: 'living',
    deviceId: 'livingBlind1',
    displayName: 'Living blind right',
    store: writable<NumberDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    readTopic: env.PUBLIC_LIVING_BLIND_1_FROM,
    writeTopic: env.PUBLIC_LIVING_BLIND_1_TO,
    deviceType: 'blind',
    type: 'number',
  },
  {
    roomId: 'living',
    deviceId: 'livingBlind2',
    displayName: 'Living blind left',
    store: writable<NumberDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    readTopic: env.PUBLIC_LIVING_BLIND_2_FROM,
    writeTopic: env.PUBLIC_LIVING_BLIND_2_TO,
    deviceType: 'blind',
    type: 'number',
  },
  {
    roomId: 'dining',
    deviceId: 'diningLight',
    displayName: 'Dining light',
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    readTopic: env.PUBLIC_DINING_LIGHT_FROM,
    writeTopic: env.PUBLIC_DINING_LIGHT_TO,
    deviceType: 'light',
    type: 'boolean',
  },
  {
    roomId: 'dining',
    deviceId: 'diningPresence',
    displayName: 'Dining presence',
    readTopic: env.PUBLIC_DINING_PRESENCE,
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'presence',
    type: 'boolean',
  }, 
  {
    roomId: 'dining',
    deviceId: 'diningBlind',
    displayName: 'Dining blind',
    store: writable<NumberDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    readTopic: env.PUBLIC_DINING_BLIND_FROM,
    writeTopic: env.PUBLIC_DINING_BLIND_TO,
    deviceType: 'blind',
    type: 'number',
  },
  {
    roomId: 'livingGarden',
    deviceId: 'livingGardenLight',
    displayName: 'Living garden light',
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    readTopic: env.PUBLIC_LIVING_GARDEN_LIGHT_FROM,
    writeTopic: env.PUBLIC_LIVING_GARDEN_LIGHT_TO,
    deviceType: 'light',
    type: 'boolean',
  },
  {
    roomId: 'kitchen',
    deviceId: 'kitchenLight',
    displayName: 'Kitchen light',
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    readTopic: env.PUBLIC_KITCHEN_LIGHT_FROM,
    writeTopic: env.PUBLIC_KITCHEN_LIGHT_TO,
    deviceType: 'light',
    type: 'boolean',
  },
  {
    roomId: 'kitchen',
    deviceId: 'kitchenBlind',
    displayName: 'Kitchen blind',
    store: writable<NumberDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    readTopic: env.PUBLIC_KITCHEN_BLIND_FROM,
    writeTopic: env.PUBLIC_KITCHEN_BLIND_TO,
    deviceType: 'blind',
    type: 'number',
  },
  {
    roomId: 'store',
    deviceId: 'storeLight',
    displayName: 'Store light',
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    readTopic: env.PUBLIC_STORE_LIGHT_FROM,
    writeTopic: env.PUBLIC_STORE_LIGHT_TO,
    deviceType: 'light',
    type: 'boolean',
  },
  {
    roomId: 'store',
    deviceId: 'storeTemperature',
    displayName: 'Store temperature',
    readTopic: env.PUBLIC_STORE_TEMP,
    store: writable<NumberDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'temperature',
    type: 'number',
  },
  {
    roomId: 'store',
    deviceId: 'storePresence',
    displayName: 'Store presence',
    readTopic: env.PUBLIC_STORE_PRESENCE,
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'presence',
    type: 'boolean',
  },
  {
    roomId: 'entrance',
    deviceId: 'entranceLight',
    displayName: 'Entrance light',
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    readTopic: env.PUBLIC_ENTRANCE_LIGHT_FROM,
    writeTopic: env.PUBLIC_ENTRANCE_LIGHT_TO,
    deviceType: 'light',
    type: 'boolean',
  },
  {
    roomId: 'entrance',
    deviceId: 'entranceHeating',
    displayName: 'Entrance heating',
    readTopic: env.PUBLIC_ENTRANCE_HEAT_VALVE,
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'heating',
    type: 'boolean',
  },
  {
    roomId: 'entrance',
    deviceId: 'entranceTemperature',
    displayName: 'Entrance temperature',
    readTopic: env.PUBLIC_ENTRANCE_TEMP,
    store: writable<NumberDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'temperature',
    type: 'number',
  },
  {
    roomId: 'entrance',
    deviceId: 'entranceSetTemperature',
    displayName: 'Entrance set temperature',
    readTopic: env.PUBLIC_ENTRANCE_SET_TEMP,
    store: writable<NumberDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'setTemperature',
    type: 'number',
  },
  {
    roomId: 'entrance',
    deviceId: 'entrancePresence',
    displayName: 'Entrance presence',
    readTopic: env.PUBLIC_ENTRANCE_PRESENCE,
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'presence',
    type: 'boolean',
  },
  {
    roomId: 'bath0',
    deviceId: 'bath0Light',
    displayName: 'Bath0 light',
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    readTopic: env.PUBLIC_BATH_0_LIGHT_FROM,
    writeTopic: env.PUBLIC_BATH_0_LIGHT_TO,
    deviceType: 'light',
    type: 'boolean',
  },
  {
    roomId: 'bath0',
    deviceId: 'bath0MirrorLight',
    displayName: 'Bath0 mirror light',
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    readTopic: env.PUBLIC_BATH_0_MIRROR_LIGHT_FROM,
    writeTopic: env.PUBLIC_BATH_0_MIRROR_LIGHT_TO,
    deviceType: 'light',
    type: 'boolean',
  },
  {
    roomId: 'bath0',
    deviceId: 'bath0Temperature',
    displayName: 'Bath0 temperature',
    readTopic: env.PUBLIC_BATH_0_TEMP,
    store: writable<NumberDeviceState>('error'),
    rawStore: writable<string>(),
    deviceType: 'temperature',
    type: 'number',
  },
  {
    roomId: 'bath0',
    deviceId: 'bath0SetTemperature',
    displayName: 'Bath0 set temperature',
    readTopic: env.PUBLIC_BATH_0_SET_TEMP,
    store: writable<NumberDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'setTemperature',
    type: 'number',
  },
  {
    roomId: 'bath0',
    deviceId: 'bath0Heating',
    displayName: 'Bath0 heating',
    readTopic: env.PUBLIC_BATH_0_HEAT_VALVE,
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'heating',
    type: 'boolean',
  },
  {
    roomId: 'bath0',
    deviceId: 'bath0Blind',
    displayName: 'Bath0 blind',
    store: writable<NumberDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    readTopic: env.PUBLIC_BATH_0_BLIND_FROM,
    writeTopic: env.PUBLIC_BATH_0_BLIND_TO,
    deviceType: 'blind',
    type: 'number',
  },
  {
    roomId: 'bath0',
    deviceId: 'bath0Presence',
    displayName: 'Bath0 presence',
    readTopic: env.PUBLIC_BATH_0_PRESENCE,
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'presence',
    type: 'boolean',
  },
  {
    roomId: 'boiler',
    deviceId: 'boilerTemperature',
    displayName: 'Boiler temperature',
    readTopic: env.PUBLIC_BOILER_TEMP,
    store: writable<NumberDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'temperature',
    type: 'number',
  },
  {
    roomId: 'boiler',
    deviceId: 'boilerLight',
    displayName: 'Boiler light',
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    readTopic: env.PUBLIC_BOILER_LIGHT_FROM,
    writeTopic: env.PUBLIC_BOILER_LIGHT_TO,
    deviceType: 'light',
    type: 'boolean',
  },
  {
    roomId: 'boiler',
    deviceId: 'boilerWallLight',
    displayName: 'Boiler wall light',
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    readTopic: env.PUBLIC_BOILER_WALL_LIGHT_FROM,
    writeTopic: env.PUBLIC_BOILER_WALL_LIGHT_TO,
    deviceType: 'light',
    type: 'boolean',
  },
  {
    roomId: 'boiler',
    deviceId: 'boilerPresence',
    displayName: 'Boiler presence',
    readTopic: env.PUBLIC_BOILER_PRESENCE,
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'presence',
    type: 'boolean',
  },
  {
    roomId: 'hall0',
    deviceId: 'hall0Light',
    displayName: 'Hall0 light',
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    readTopic: env.PUBLIC_HALL_0_LIGHT_FROM,
    writeTopic: env.PUBLIC_HALL_0_LIGHT_TO,
    deviceType: 'light',
    type: 'boolean',
  },
  {
    roomId: 'stairs',
    deviceId: 'stairsLight',
    displayName: 'Stairs light',
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    readTopic: env.PUBLIC_STAIRS_LIGHT_FROM,
    writeTopic: env.PUBLIC_STAIRS_LIGHT_TO,
    deviceType: 'light',
    type: 'boolean',
  },
  {
    roomId: 'garage',
    deviceId: 'garageLight0',
    displayName: 'Garage light 0',
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    readTopic: env.PUBLIC_GARAGE_LIGHT_0_FROM,
    writeTopic: env.PUBLIC_GARAGE_LIGHT_0_TO,
    deviceType: 'light',
    type: 'boolean',
  },
  {
    roomId: 'garage',
    deviceId: 'garageLight1',
    displayName: 'Garage light 1',
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    readTopic: env.PUBLIC_GARAGE_LIGHT_1_FROM,
    writeTopic: env.PUBLIC_GARAGE_LIGHT_1_TO,
    deviceType: 'light',
    type: 'boolean',
  },
  {
    roomId: 'garage',
    deviceId: 'garageTemperature',
    displayName: 'Garage temperature',
    readTopic: env.PUBLIC_GARAGE_TEMP,
    store: writable<NumberDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'temperature',
    type: 'number',
  },
  {
    roomId: 'garage',
    deviceId: 'garageSetTemperature',
    displayName: 'Garage set temperature',
    readTopic: env.PUBLIC_GARAGE_SET_TEMP,
    store: writable<NumberDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'setTemperature',
    type: 'number',
  },
  {
    roomId: 'garage',
    deviceId: 'garageHeating',
    displayName: 'Garage heating',
    readTopic: env.PUBLIC_GARAGE_HEAT_VALVE,
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'heating',
    type: 'boolean',
  },
  {
    roomId: 'garage',
    deviceId: 'garagePresence',
    displayName: 'Garage presence',
    readTopic: env.PUBLIC_GARAGE_PRESENCE,
    store: writable<BooleanDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'presence',
    type: 'boolean',
  },
  {
    roomId: 'external',
    deviceId: 'externalTemperature',
    displayName: 'External temperature',
    readTopic: env.PUBLIC_EXTERNAL_TEMP,
    store: writable<NumberDeviceState>('not-initialized'),
    rawStore: writable<string>(),
    deviceType: 'temperature',
    type: 'number',
  },
]

export type DeviceType = 'temperature' | 'setTemperature' | 'heating' | 'light' | 'blind' | 'presence'
export type DeviceWritable<T> = T extends 'heating' | 'light' ? Writable<BooleanDeviceState> : T extends 'temperature' | 'setTemperature' ? Writable<NumberDeviceState> : never


export function findDeviceStore<T extends DeviceType>(
  roomId: string,
  deviceType: T
): DeviceWritable<T> | undefined {
  const deviceConfig = configuration.find((config) => config.roomId === roomId && config.deviceType === deviceType)

  if (!deviceConfig) {
    return undefined
  }

  if(deviceType === 'light' || deviceType === 'heating' || deviceType === 'presence' || deviceType === 'blind') {
    return deviceConfig.store as unknown as DeviceWritable<T>
  }

  if (deviceType === 'setTemperature' || deviceType === 'temperature') {
    return deviceConfig.store as unknown as DeviceWritable<T>
  }

  return undefined
}

export function findDeviceMetadata(
  roomId: string,
  deviceType: DeviceType,
  deviceId?: string
): DeviceMetadata | undefined {
  const deviceConfig =  deviceId 
    ? configuration.find((config) => config.roomId === roomId && config.deviceType === deviceType && config.deviceId === deviceId) 
    : configuration.find((config) => config.roomId === roomId && config.deviceType === deviceType)

  if (!deviceConfig) {
    return undefined
  }

  return {
    deviceId: deviceConfig.deviceId,
    readTopic: deviceConfig.readTopic,
    writeTopic: deviceConfig.writeTopic,
  }
}
